<?php
namespace Tests\Feature;
use App\NewsArticle;use App\NewsSource;use App\Services\News\NewsFeedService;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Carbon;use Illuminate\Support\Facades\Http;use Tests\TestCase;
class NewsTest extends TestCase
{
 use RefreshDatabase;
 public function testNavigationLinksToPublicNewsWithoutExposingAdminLink(){ $this->get(route('tv'))->assertOk()->assertSee('href="'.route('news.index').'"',false);$this->get(route('news.index'))->assertOk()->assertDontSee('href="'.route('admin.news.index').'"',false)->assertDontSee('Administrer nyheter'); }
 public function testPublicPageShowsAllFreshPublishedArticlesAcrossSourcesInPublicationOrder(){ $no=$this->source('Norge');$se=$this->source('Sverige','se');$dk=$this->source('Danmark','dk');$this->article($no,'Eldst',NewsArticle::STATUS_PUBLISHED,['published_at'=>now('Europe/Oslo')->subHours(3)]);$this->article($se,'Nyest',NewsArticle::STATUS_PUBLISHED,['published_at'=>now('Europe/Oslo')->subHour()]);$this->article($dk,'Mellom',NewsArticle::STATUS_PUBLISHED,['published_at'=>now('Europe/Oslo')->subHours(2)]);foreach(['pending','hidden','archived'] as $status)$this->article($no,ucfirst($status),$status);$this->get('/nyheter')->assertOk()->assertSeeInOrder(['Nyest','Mellom','Eldst'])->assertSee('Kilde se')->assertSee('Kilde dk')->assertDontSee('Pending')->assertDontSee('Hidden')->assertDontSee('Archived')->assertDontSee('Filtrer nyheter etter land'); }
 public function testPublicPageHidesArticlesOlderThanTenDaysAndUsesStableFallbackDate(){ Carbon::setTestNow(Carbon::create(2026,10,8,12,0,0,'Europe/Oslo')); try {$source=$this->source('Norge');$this->article($source,'På ti-døgnsgrensen',NewsArticle::STATUS_PUBLISHED,['published_at'=>now('Europe/Oslo')->subDays(10)]);$this->article($source,'For gammel',NewsArticle::STATUS_PUBLISHED,['published_at'=>now('Europe/Oslo')->subDays(10)->subSecond()]);$this->article($source,'Mangler dato men er fersk',NewsArticle::STATUS_PUBLISHED,['published_at'=>null,'fetched_at'=>now('Europe/Oslo')->subDays(9)]);$this->article($source,'Mangler dato og er gammel',NewsArticle::STATUS_PUBLISHED,['published_at'=>null,'fetched_at'=>now('Europe/Oslo')->subDays(11)]);$this->get('/nyheter')->assertOk()->assertSee('På ti-døgnsgrensen')->assertSee('Mangler dato men er fersk')->assertDontSee('For gammel')->assertDontSee('Mangler dato og er gammel');} finally {Carbon::setTestNow();} }
 public function testRepeatedFetchWithoutPublicationDateDoesNotMakeAnExpiredArticlePublicAgain(){ Carbon::setTestNow(Carbon::create(2026,10,1,12,0,0,'Europe/Oslo')); try {$source=$this->source('Norge','without-date');$url='https://feed.test/without-date';$source->update(['feed_url'=>$url]);$rss='<rss version="2.0"><channel><item><guid>without-date</guid><title>Manglende publiseringsdato</title><link>https://example.test/without-date</link></item></channel></rss>';Http::fake([$url=>Http::response($rss,200)]);$service=app(NewsFeedService::class);$this->assertSame(1,$service->fetch($source)['new']);$article=NewsArticle::where('news_source_id',$source->id)->first();$article->update(['status'=>NewsArticle::STATUS_PUBLISHED]);$initialFetchedAt=$article->fetched_at->copy();Carbon::setTestNow(now('Europe/Oslo')->addDays(11));$this->assertSame(1,$service->fetch($source->fresh())['duplicates']);$this->assertTrue($initialFetchedAt->equalTo($article->fresh()->fetched_at));$this->get('/nyheter')->assertOk()->assertDontSee('Manglende publiseringsdato');} finally {Carbon::setTestNow();} }
 public function testPaginationWorks(){ $s=$this->source('Norge');foreach(range(1,13) as $i)$this->article($s,'Artikkel '.$i,NewsArticle::STATUS_PUBLISHED,['published_at'=>now()->subMinutes($i)]);$this->get('/nyheter')->assertOk()->assertSee('page=2',false); }
 public function testAdminRequiresAuthentication(){ $this->get('/admin/nyheter')->assertRedirect(route('admin.login'));$this->get('/admin/nyheter/kilder')->assertRedirect(route('admin.login')); }
 public function testAdminCanPublishAndEditPublicText(){ $s=$this->source('Norge');$a=$this->article($s,'Original',NewsArticle::STATUS_PENDING);$admin=$this->withSession(['admin_authenticated'=>true]);$admin->patch(route('admin.news.update',$a),['edited_title'=>'Redigert','edited_excerpt'=>'Ny ingress'])->assertSessionHas('success');$admin->patch(route('admin.news.status',$a),['status'=>'published'])->assertSessionHas('success');$this->get('/nyheter')->assertSee('Redigert')->assertSee('Ny ingress')->assertDontSee('Original'); }
 public function testDisabledSourcesAreNotFetched(){ $this->source('Norge','inactive',false);Http::fake();$this->artisan('news:fetch')->assertExitCode(0);Http::assertNothingSent(); }
 public function testNewsSourceSeederCanRunTwiceWithoutDuplicates(){ $this->artisan('db:seed',['--class'=>'NewsSourceSeeder'])->assertExitCode(0);$this->artisan('db:seed',['--class'=>'NewsSourceSeeder'])->assertExitCode(0);$this->assertSame(4,NewsSource::count());$this->assertDatabaseHas('news_sources',['slug'=>'nff-magasinet','website_url'=>'https://www.frifagbevegelse.no/nff-magasinet','feed_url'=>'https://www.frifagbevegelse.no/nff-magasinet/?lab_viewport=rss']); }
 private function source($country,$slug='source',$active=true){return NewsSource::create(['name'=>'Kilde '.$slug,'slug'=>$slug,'country'=>$country,'website_url'=>'https://example.test','feed_url'=>'https://example.test/feed','source_type'=>'rss','is_active'=>$active]);}
 private function article($source,$title,$status,$extra=[]){return NewsArticle::create(array_merge(['news_source_id'=>$source->id,'original_url'=>'https://example.test/'.strtolower(str_replace(' ','-',$title)).uniqid(),'normalized_url'=>'https://example.test/'.uniqid(),'original_title'=>$title,'original_excerpt'=>'Ingress '.$title,'fetched_at'=>now(),'published_at'=>now(),'status'=>$status],$extra));}
}
