<?php
namespace Tests\Feature;
use App\NewsArticle;use App\NewsSource;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Http;use Tests\TestCase;
class NewsTest extends TestCase
{
 use RefreshDatabase;
 public function testNavigationLinksToPublicAndAdminNewsPages(){ $this->get(route('tv'))->assertOk()->assertSee('href="'.route('news.index').'"',false);$this->get(route('news.index'))->assertOk()->assertSee('href="'.route('admin.news.index').'"',false); }
 public function testPublicPageOnlyShowsPublishedAndSupportsCountryFilter(){ $no=$this->source('Norge');$se=$this->source('Sverige','se');$published=$this->article($no,'Publisert',NewsArticle::STATUS_PUBLISHED);foreach(['pending','hidden','archived'] as $status)$this->article($no,ucfirst($status),$status);$this->article($se,'Svensk publisert',NewsArticle::STATUS_PUBLISHED);$this->get('/nyheter?land=norge')->assertOk()->assertSee('Publisert')->assertDontSee('Svensk publisert')->assertDontSee('Pending')->assertDontSee('Hidden')->assertDontSee('Archived'); }
 public function testPaginationWorks(){ $s=$this->source('Norge');foreach(range(1,13) as $i)$this->article($s,'Artikkel '.$i,NewsArticle::STATUS_PUBLISHED,['published_at'=>now()->subMinutes($i)]);$this->get('/nyheter')->assertOk()->assertSee('page=2',false); }
 public function testAdminRequiresAuthentication(){ $this->get('/admin/nyheter')->assertRedirect(route('admin.login'));$this->get('/admin/nyheter/kilder')->assertRedirect(route('admin.login')); }
 public function testAdminCanPublishHideArchiveAndEditPublicText(){ $s=$this->source('Norge');$a=$this->article($s,'Original',NewsArticle::STATUS_PENDING);$admin=$this->withSession(['admin_authenticated'=>true]);$admin->patch(route('admin.news.update',$a),['edited_title'=>'Redigert','edited_excerpt'=>'Ny ingress'])->assertSessionHas('success');$admin->patch(route('admin.news.status',$a),['status'=>'published'])->assertSessionHas('success');$this->get('/nyheter')->assertSee('Redigert')->assertSee('Ny ingress')->assertDontSee('Original');$admin->patch(route('admin.news.status',$a),['status'=>'hidden']);$this->assertSame('hidden',$a->fresh()->status);$admin->patch(route('admin.news.status',$a),['status'=>'archived']);$this->assertSame('archived',$a->fresh()->status);$admin->patch(route('admin.news.status',$a),['status'=>'pending']);$this->assertSame('pending',$a->fresh()->status); }
 public function testDisabledSourcesAreNotFetched(){ $this->source('Norge','inactive',false);Http::fake();$this->artisan('news:fetch')->assertExitCode(0);Http::assertNothingSent(); }
 public function testNewsSourceSeederCanRunTwiceWithoutDuplicates(){ $this->artisan('db:seed',['--class'=>'NewsSourceSeeder'])->assertExitCode(0);$this->artisan('db:seed',['--class'=>'NewsSourceSeeder'])->assertExitCode(0);$this->assertSame(4,NewsSource::count());$this->assertDatabaseHas('news_sources',['slug'=>'nff-magasinet']); }
 private function source($country,$slug='source',$active=true){return NewsSource::create(['name'=>'Kilde '.$slug,'slug'=>$slug,'country'=>$country,'website_url'=>'https://example.test','feed_url'=>'https://example.test/feed','source_type'=>'rss','is_active'=>$active]);}
 private function article($source,$title,$status,$extra=[]){return NewsArticle::create(array_merge(['news_source_id'=>$source->id,'original_url'=>'https://example.test/'.strtolower(str_replace(' ','-',$title)).uniqid(),'normalized_url'=>'https://example.test/'.uniqid(),'original_title'=>$title,'original_excerpt'=>'Ingress '.$title,'fetched_at'=>now(),'published_at'=>now(),'status'=>$status],$extra));}
}
