@extends('layouts.app')

@section('title', 'Nations League | INNSATT.NO')

@push('styles')
<style>
    .nl-page { background:#f6f7f9; min-height:100vh; } .nl-hero,.nl-section { background:#fff; border:1px solid #dde2e8; border-radius:6px; }
    .nl-muted,.nl-status { color:#667085; } .nl-table th { background:#eef2f6; color:#2d3748; font-size:.82rem; white-space:nowrap; } .nl-table td { vertical-align:middle; white-space:nowrap; }
    .nl-team,.nl-match-team { align-items:center; display:flex; gap:.45rem; } .nl-team { min-width:145px; white-space:normal; } .nl-team-link { color:inherit; text-decoration:none; } .nl-team-link:hover,.nl-team-link:focus { text-decoration:underline; }
    .nl-emblem { height:24px; object-fit:contain; width:24px; } .nl-match-emblem { height:18px; object-fit:contain; width:18px; } .nl-match { border-top:1px solid #e6eaf0; padding:.65rem 0; } .nl-match:first-child { border-top:0; }
    .nl-match-row { display:flex; justify-content:space-between; } .nl-match-row > * + * { margin-left:1rem; } .nl-match-teams { display:grid; gap:.35rem; } .nl-score { font-weight:700; min-width:3.75rem; text-align:right; }
    .nl-empty { background:#f8fafc; border:1px dashed #cbd5e1; border-radius:6px; color:#536173; margin-bottom:0; padding:1rem; } .nl-rule { color:#536173; font-size:.75rem; white-space:normal; } .nl-norway { background:#eef6ff; font-weight:700; } .nl-group { break-inside:avoid; page-break-inside:avoid; }
    @media (max-width:575.98px) { .nl-hero,.nl-section { border-left:0; border-right:0; border-radius:0; } }
</style>
@endpush

@section('content')
<div class="nl-page"><div class="container py-4 py-md-5">
@include('partials.header')
<section class="nl-hero p-3 p-md-4 mb-3"><div class="d-flex flex-wrap align-items-start justify-content-between"><div><h1 class="h2 mb-2">{{ $competitionName }}</h1><p class="lead mb-2">{{ $seasonLabel }} · grupper, kamper og resultater hentet fra VG/Schibsted sitt sports-API.</p>@if($lastUpdated)<p class="nl-muted mb-0">Sist oppdatert: {{ $lastUpdated->format('d.m.Y H:i') }}</p>@endif</div><a href="{{ route('nations-league.print') }}" class="btn btn-success mt-2 mt-md-0"><i class="far fa-print" aria-hidden="true"></i> Skriv ut oversikt</a></div>
@if(!$apiConfigured)<p class="nl-empty mt-3">Nations League-sesongen er ikke koblet til en sikker Schibsted-sesong-ID ennå.</p>@elseif($apiError && !$usingStaleData)<p class="nl-empty mt-3">Vi klarer ikke hente oppdaterte Nations League-data akkurat nå. Prøv igjen senere.</p>@elseif($apiError)<p class="nl-empty mt-3">Nye data kunne ikke hentes akkurat nå. Viser sist lagrede data.</p>@endif</section>
@include('football.partials.tv-matches-box', ['tvBoxContext' => 'nations-league-overview'])

<section class="nl-section p-3 p-md-4 mb-3"><h2 class="h4 mb-1">Norge</h2><p class="nl-muted mb-3">Norge spiller i {{ $norwayGroup['stageName'] ?? 'sin Nations League-gruppe' }}.</p>
@if($norwayGroup)<div class="table-responsive"><table class="table table-sm table-bordered nl-table mb-0"><thead><tr><th>Plass</th><th>Lag</th><th class="text-center">K</th><th class="text-center">V</th><th class="text-center">U</th><th class="text-center">T</th><th class="text-center">Mål</th><th class="text-center">MF</th><th class="text-center">P</th><th>Mulighet</th></tr></thead><tbody>@foreach($norwayGroup['rows'] as $team)<tr class="{{ (int)$team['teamId']===$norwayTeamId?'nl-norway':'' }}"><td>{{ $team['rank'] ?? '-' }}</td><td><a class="nl-team nl-team-link" href="{{ route('nations-league.team',$team['teamId']) }}">@if($team['emblemUrl'])<img class="nl-emblem" src="{{ $team['emblemUrl'] }}" alt="" onerror="this.remove()">@endif{{ $team['teamName'] }}</a></td><td class="text-center">{{ $team['played'] ?? '-' }}</td><td class="text-center">{{ $team['wins'] ?? '-' }}</td><td class="text-center">{{ $team['draws'] ?? '-' }}</td><td class="text-center">{{ $team['losses'] ?? '-' }}</td><td class="text-center">{{ $team['goalsFor'] ?? '-' }}-{{ $team['goalsAgainst'] ?? '-' }}</td><td class="text-center">{{ $team['goalDifference'] ?? '-' }}</td><td class="text-center"><strong>{{ $team['points'] ?? '-' }}</strong></td><td class="nl-rule">{{ $team['rule']['name'] ?? '' }}</td></tr>@endforeach</tbody></table></div>@else<p class="nl-empty">Norges gruppe er ikke publisert i datagrunnlaget ennå.</p>@endif</section>

<section class="nl-section p-3 p-md-4 mb-3"><h2 class="h4 mb-3">Denne ukens kamper</h2>@forelse($weekFixturesByDate as $date=>$matches)<h3 class="h6 mt-3 mb-2">{{ $date }}</h3>@foreach($matches as $match)<div class="nl-match"><div class="nl-match-row"><div><div class="nl-status">{{ $match['timeLabel'] }}@if($match['round']) · Runde {{ $match['round'] }}@endif</div><div class="nl-match-teams"><a class="nl-team-link nl-match-team" href="{{ route('nations-league.team',$match['homeTeamId']) }}">@if($match['homeEmblemUrl'])<img class="nl-match-emblem" src="{{ $match['homeEmblemUrl'] }}" alt="" onerror="this.remove()">@endif{{ $match['homeTeam'] }}</a><a class="nl-team-link nl-match-team" href="{{ route('nations-league.team',$match['awayTeamId']) }}">@if($match['awayEmblemUrl'])<img class="nl-match-emblem" src="{{ $match['awayEmblemUrl'] }}" alt="" onerror="this.remove()">@endif{{ $match['awayTeam'] }}</a></div></div>@if($match['isFinished'])<div class="nl-score">{{ $match['homeScore'] ?? '-' }} - {{ $match['awayScore'] ?? '-' }}</div>@endif</div></div>@endforeach @empty <p class="nl-empty">Det er ingen Nations League-kamper denne kalenderuken.</p>@endforelse</section>

<section class="nl-section p-3 p-md-4 mb-3"><h2 class="h4 mb-3">Resultater</h2>@forelse($recentResultsByDate as $date=>$matches)<h3 class="h6 mt-3 mb-2">{{ $date }}</h3>@foreach($matches as $match)<div class="nl-match"><div class="nl-match-row"><div><div class="nl-status">{{ $match['round'] ? 'Runde '.$match['round'] : 'Ferdigspilt' }}</div><div class="nl-match-teams"><a class="nl-team-link nl-match-team" href="{{ route('nations-league.team',$match['homeTeamId']) }}">{{ $match['homeTeam'] }}</a><a class="nl-team-link nl-match-team" href="{{ route('nations-league.team',$match['awayTeamId']) }}">{{ $match['awayTeam'] }}</a></div></div><div class="nl-score">{{ $match['homeScore'] ?? '-' }} - {{ $match['awayScore'] ?? '-' }}</div></div></div>@endforeach @empty <p class="nl-empty">Ingen ferdigspilte kamper er publisert ennå.</p>@endforelse</section>

<section class="nl-section p-3 p-md-4 mb-3"><h2 class="h4 mb-1">Grupper og tabeller</h2><p class="nl-muted mb-3">Gruppebetegnelsene og mulighetene for sluttspill, kvalifisering, opprykk og nedrykk kommer direkte fra SportsNext.</p><div class="row">@forelse($standingsGroups as $group)<div class="col-md-6 col-xl-4 mb-3"><section class="nl-group border rounded p-2 h-100"><h3 class="h6 mb-2">{{ $group['stageName'] ?? 'Gruppe '.$group['groupName'] }}</h3><div class="table-responsive"><table class="table table-sm mb-0 nl-table"><thead><tr><th>#</th><th>Lag</th><th class="text-center">K</th><th class="text-center">MF</th><th class="text-center">P</th></tr></thead><tbody>@foreach($group['rows'] as $team)<tr class="{{ (int)$team['teamId']===$norwayTeamId?'nl-norway':'' }}"><td>{{ $team['rank'] ?? '-' }}</td><td><a class="nl-team nl-team-link" href="{{ route('nations-league.team',$team['teamId']) }}">@if($team['emblemUrl'])<img class="nl-emblem" src="{{ $team['emblemUrl'] }}" alt="" onerror="this.remove()">@endif{{ $team['teamName'] }}</a>@if(!empty($team['rule']['name']))<div class="nl-rule">{{ $team['rule']['name'] }}</div>@endif</td><td class="text-center">{{ $team['played'] ?? '-' }}</td><td class="text-center">{{ $team['goalDifference'] ?? '-' }}</td><td class="text-center"><strong>{{ $team['points'] ?? '-' }}</strong></td></tr>@endforeach</tbody></table></div></section></div>@empty <div class="col"><p class="nl-empty">Gruppene er ikke publisert i datagrunnlaget ennå.</p></div>@endforelse</div></section>
@include('partials.footer')</div></div>
@endsection
