<?php
namespace Tests\Unit;
use App\NewsArticle;
use App\NewsSource;
use App\Services\News\NewsFeedService;
use App\Services\News\Parsers\SekoHtmlParser;
use App\Services\News\UrlNormalizer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;
class NewsFeedTest extends TestCase
{
 use RefreshDatabase;
 public function testUrlNormalizationAndTrackingRemoval(){ $n=app(UrlNormalizer::class); $this->assertSame('https://example.test/path?a=1',$n->normalize('HTTPS://Example.Test/path?utm_source=x&a=1&fbclid=y')); $this->assertNull($n->normalize('javascript:alert(1)')); }
 public function testRssParsingSanitizingValidationAndDuplicates(){ $s=$this->source(['source_type'=>'rss','feed_url'=>'https://feed.test/rss']); Http::fake(['https://feed.test/rss'=>Http::response($this->fixture('rss.xml'),200)]); $service=app(NewsFeedService::class); $first=$service->fetch($s); $second=$service->fetch($s->fresh()); $this->assertSame(3,$first['found']); $this->assertSame(1,$first['new']); $this->assertSame(1,$second['duplicates']); $a=NewsArticle::first(); $this->assertSame('Kort ingress.',$a->original_excerpt); $this->assertSame('https://example.test/story',$a->normalized_url); $this->assertSame(NewsArticle::normalizedUrlHash($a->normalized_url),$a->normalized_url_hash); $this->assertDatabaseMissing('news_articles',['original_title'=>'Ingen lenke']); }
 public function testNormalizedUrlHashSupportsLongUrlsAndIsUniquePerSource(){ $s=$this->source(); $url='https://example.test/'.str_repeat('a',1900); $article=NewsArticle::create(['news_source_id'=>$s->id,'original_url'=>$url,'normalized_url'=>$url,'original_title'=>'Lang URL','fetched_at'=>now()]); $this->assertSame(hash('sha256',$url),$article->normalized_url_hash); $this->expectException(\Illuminate\Database\QueryException::class); NewsArticle::create(['news_source_id'=>$s->id,'original_url'=>$url,'normalized_url'=>$url,'original_title'=>'Dublett','fetched_at'=>now()]); }
 public function testExternalIdDuplicateCheckStillWinsWhenUrlChanges(){ $s=$this->source(['feed_url'=>'https://feed.test/rss']); Http::fake(['https://feed.test/rss'=>Http::response($this->fixture('rss.xml'),200)]); NewsArticle::create(['news_source_id'=>$s->id,'external_id'=>'item-1','original_url'=>'https://old.example/story','normalized_url'=>'https://old.example/story','original_title'=>'Fra før','fetched_at'=>now()]); $report=app(NewsFeedService::class)->fetch($s); $this->assertSame(0,$report['new']); $this->assertSame(1,$report['duplicates']); }
 public function testAtomParsing(){ $s=$this->source(['source_type'=>'atom','feed_url'=>'https://feed.test/atom']); Http::fake(['https://feed.test/atom'=>Http::response($this->fixture('atom.xml'),200)]); $this->assertSame(1,app(NewsFeedService::class)->fetch($s)['new']); $this->assertDatabaseHas('news_articles',['external_id'=>'atom-1','original_author'=>'Anna']); }
 public function testCorrectionsHtmlParsing(){ $s=$this->source(['slug'=>'corrections1','source_type'=>'html','feed_url'=>'https://feed.test/html']); Http::fake(['https://feed.test/html'=>Http::response($this->fixture('corrections1.html'),200)]); $this->assertSame(1,app(NewsFeedService::class)->fetch($s)['new']); $this->assertDatabaseHas('news_articles',['original_title'=>'Training in corrections','original_excerpt'=>'Safe practice']); }
 public function testSekoRelevanceIsLimitedToCorrectionsArticles(){ $parser=app(SekoHtmlParser::class); $this->assertTrue($parser->isRelevantSekoArticle(['title'=>'Hot, våld och ensamarbete inom Kriminalvården'])); $this->assertTrue($parser->isRelevantSekoArticle(['title'=>'Ny rapport från Seko','excerpt'=>'Rapporten beskriver bemanningen på svenska häkten.'])); $this->assertTrue($parser->isRelevantSekoArticle(['title'=>'Avtalet är klart','url'=>'https://www.seko.se/nyheter/2026/juni/kriminalvarden/avtal-klart/'])); $this->assertFalse($parser->isRelevantSekoArticle(['title'=>'Nu startar medlemsveckan!','excerpt'=>'Träffa Seko på din arbetsplats.'])); $this->assertFalse($parser->isRelevantSekoArticle(['title'=>'En bättre arbetsmiljö','excerpt'=>'Alla medlemmar ska känna sig trygga på jobbet.'])); }
 public function testSekoHtmlParsingFiltersForCorrectionsRelevance(){ $s=$this->source(['slug'=>'seko-kriminalvarden','source_type'=>'html','feed_url'=>null,'website_url'=>'https://seko.test/vard']); Http::fake(['https://seko.test/vard'=>Http::response($this->fixture('seko.html'),200)]); $report=app(NewsFeedService::class)->fetch($s); $this->assertSame(3,$report['found']); $this->assertSame(3,$report['new']); $this->assertDatabaseHas('news_articles',['original_title'=>'Hot, våld och ensamarbete inom Kriminalvården']); $this->assertDatabaseHas('news_articles',['original_title'=>'Ny rapport från Seko']); $this->assertDatabaseHas('news_articles',['original_title'=>'Avtalet är klart']); $this->assertDatabaseMissing('news_articles',['original_title'=>'Nu startar medlemsveckan!']); $this->assertDatabaseMissing('news_articles',['original_title'=>'En bättre arbetsmiljö']); }
 public function testFailureInOneSourceDoesNotStopAnother(){ $this->source(['slug'=>'bad','feed_url'=>'https://feed.test/bad']); $this->source(['slug'=>'good','feed_url'=>'https://feed.test/good']); Http::fake(['https://feed.test/bad'=>Http::response('down',500),'https://feed.test/good'=>Http::response($this->fixture('rss.xml'),200)]); $reports=app(NewsFeedService::class)->fetchActive(); $this->assertCount(2,$reports); $this->assertNotNull(collect($reports)->firstWhere('slug','bad')['error']); $this->assertSame(1,collect($reports)->firstWhere('slug','good')['new']); }
 private function source(array $overrides=[]){ static $i=0;$i++;return NewsSource::create(array_merge(['name'=>'Source '.$i,'slug'=>'source-'.$i,'country'=>'Norge','website_url'=>'https://source.test','feed_url'=>'https://feed.test/'.$i,'source_type'=>'rss','is_active'=>true],$overrides)); }
 private function fixture($name){return file_get_contents(base_path('tests/Fixtures/news/'.$name));}
}
